name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Xcode Build
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        project: expenses.xcodeproj
